### ISSUE TITLE
About convolutional operation

### ISSUE THREAD

**Issue by dongfeng951** [masa-su/Tars#70]
Hi,
   Thank you for sharing.
   I have a problem. I want to add convolutional operation to the model. However, it performs poorly. Below is my generator part code:
`z = InputLayer((None,z_dim))`
`network  = DenseLayer(z,num_units=1024,nonlinearity=activation)`
`network  = DenseLayer(network,num_units=128 * 7 * 7,nonlinearity=activation)`
`network = lasagne.layers.ReshapeLayer(network, ((-1,128,7,7)))`
`network=lasagne.layers.TransposedConv2DLayer(network,num_filters=64,\
            filter_size=(3,3),stride=(2,2),output_size=(14,14),crop='same',nonlinearity=rectify)`
`p_mean=lasagne.layers.TransposedConv2DLayer(network,1,\
            filter_size=(3,3),stride=(2,2),output_size=(28,28),crop='same',nonlinearity=sigmoid)`
`p = Deterministic(p_mean,given=[z]) #p(x|z)`
Other codes are not changed except for some minor changes to avoid error.
However, the generation is poor. 
So, how can I add conv operation, is there something wrong?
Thank you!

**Comment by masa-su** [comment]
@dongfeng951 
Hi! Thank you for using our library!

> However, it performs poorly. 

Could you tell me your problem in detail?
What model did you choose? (I think you chose the GAN class.) And what dataset did you use? 
If you used color images as the dataset in training, you should set nonlinearity of the generator's last layer as 'None' (or 'tanh' If you have already standardized your dataset).

**Comment by dongfeng951** [comment]
@masa-su 
Hi,
Thank you!
I have found the reason. I trained the model on MNIST, however, I showed the results every 20 epoch, which is too large. In fact, the best result will appear between it. Then the model will suffer overfitting and the results would become bad. When I visualize the results every 5 epoch, I can satisfactory results.
Thank you!
